name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out respository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
